### ISSUE TITLE
vscode with rtichoke

### ISSUE THREAD

**Issue by joshualeond** [REditorSupport/languageserver#11]
Hey,

Thanks for your work here. I'm currently having a problem with vscode when attempting to use `rtichoke` as the R terminal instead of the default `R.exe`. When using `rtichoke` hover-help and code completion both quit working:

![rtichoke-vscode-bug](https://user-images.githubusercontent.com/3802502/38033819-822a7042-3266-11e8-87bf-968692d994b5.gif)

Sorry if the gif is a bit hard to see. I'm just showing it working with `R.exe` and then I switch to `rtichoke` and am showing it no longer working. This is on Windows 10 by the way.

Any advice on debugging this would be appreciated. Thanks.

**Comment by randy3k** [comment]
It is not an issue of the languageserver per se. It is because [vscode-r-lsp](https://github.com/REditorSupport/vscode-r-lsp) has assumed that the [R term](https://github.com/REditorSupport/vscode-r-lsp/blob/master/src/extension.ts#L65) is used for languageserver. In fact, `vscode-r` should provide two settings, one for opening the R console, another for the default R terminal.
cc: @Ikuyadeu
