### ISSUE TITLE
incorrect highlight for variables after $

### ISSUE THREAD

**Issue by randy3k** [REditorSupport/languageserver#129]
<img width="237" alt="Screen Shot 2019-12-12 at 8 43 40 PM" src="https://user-images.githubusercontent.com/1690993/70769889-19f70700-1d20-11ea-8f69-05180221c9d5.png">

In general, it is impossible to infer what could go after $. So I guess we should just ignore everything after $.

**Comment by renkun-ken** [comment]
Do you mean document highlight? Currently, the document highlight is designed to show all tokens same with one at cursor (instead of all occurrences which might partially match), it does not try to show semantically the same token (which is not easy I believe).

**Comment by randy3k** [comment]
I meant when the variable `bar` is selected, the `bar` in `foo$bar` should not be highlighted because `bar` and `foo$bar` are semantically different.

**Comment by renkun-ken** [comment]
Currently, it does not do or say anything about semantics because when it comes to semantics, it can quickly get much complicated. 

The currently supported use case is to make it easier to search tokens rather than texts.

Do you prefer we go deeper in semantics? For example, when I choose `bar` I can pick out all `bar` not following `$` or `@`. If I choose `bar` in `foo$bar`, do we ignore it and stop providing document highlight? Personally, my main use case here is to search token, then I don't have a way to find all tokens named `bar`.

If it is too easy to get false positives and omit real results if we provide semantic highlight, then it looks like it's too unreliable, compared to token highlight which has simple and determined behavior which mainly serves as a token searcher.

**Comment by renkun-ken** [comment]
When we consider semantics, we need to define the highlight behavior for the following cases:

On each token, what other tokens do we need to highlight?

```r
foo <- list(bar = 1)
bar <- list(foo = 1)
foo$bar + bar$foo
```

**Comment by randy3k** [comment]
In general, I feel like we should avoid false positives at much as possible. I don’t mind having a few negatives due to semantics.

The current implementation is just like highlighting all the matches and we don’t even need a language server to find these matches. A regular editor plugin could do the same task more efficiently.

I think we should at least

**Comment by randy3k** [comment]
Oh, the definition code have the same issue:
```
foo$bar <- 1
bar
```
`bar` will goes to `foo$bar`.

**Comment by renkun-ken** [comment]
Good finding. Let me take a look at the definition code and hopefully I can make highlight more semantic.

**Comment by renkun-ken** [comment]
To provide a more semantic highlight, we need to consider what we should highlight when the cursor is moved to each token in the following code:

```r
bar <- 0
foo <- list(bar = 1, bar1 = 0)
foo$bar <- 2

test <- function(bar, var) {
  var$bar <- bar + 1
  bar + var$bar
}

res <- local({
  bar2 <- bar + 1
  foo$bar1 <<- 1
  bar <- 2
  bar + bar2
})

test(bar)
```

In general, we need to find the token not only in parent scopes but also children scopes. In XPath terminology, we need to find token along all ancestor and descendant nodes. However, function definitions and most function calls creates isolated scopes. Do we need to penetrate these scopes or simple ignore them, or analyze if variables inside these scopes refers to outer definition (which is probably not possible by pure XPath selection but a lot of concrete lexical analysis)?

**Comment by randy3k** [comment]
Could we check the definitions for all the token of the same name and check if they are from the same definition?

**Comment by randy3k** [comment]
```
foo <- list(bar = 1, bar1 = 0)
foo$bar <- 2
```
For this example, I would just ignore the two `bar`'s. But it would be nice to have the two `foo`'s highlighted at the same time.

**Comment by renkun-ken** [comment]
> Could we check the definitions for all the token of the same name and check if they are from the same definition?

This would be much more accurate to determine which tokens share the same semantics yet it is highly recursive because we use the last assignment above or in the line of the token. I could try this and see if works smoothly. 

Then in the following example, we would have the first two `bar` highlighted together, and the last two highlighted together, since there's a rebinding of `bar` in the middle.

```r
bar <- 1
bar2 <- bar + 1
bar <- 2
bar3 <- bar + 2
```

**Comment by randy3k** [comment]
Another thing worths mentioning. It is not necessary to search the whole file if a token is too far away from the selection, say only tokens with 50 lines of the current selection will be highlighted.

**Comment by renkun-ken** [comment]
Personally, I prefer all tokens are checked so that I can have a quick view on the scroll bar on the right. In my case, many of my scripts are quite long and I really need file-wide matches.

![image](https://user-images.githubusercontent.com/4662568/70778537-8116c900-1dbd-11ea-9bc1-9ce9f4408104.png)

I think it can only be problematic when there are too many matches, rather than far matches.

**Comment by randy3k** [comment]
Fair enough. Thank you for looking into it. I am no expert in xml, I’ll let you work on it first.

**Comment by renkun-ken** [comment]
However, the current definition does not penetrate `if`, `while`, so if the definition is used to provide highlight, then we can't see how `test` is altered in conditional branches along the way through highlight, which is not captured by definition.

```r
test <- NULL

if (foo > 0) {
  test <- 1
} else if (foo > 1) {
  test <- 2
  if (bar != 0) {
    test <- bar + 1
  }
}

test + 1
```

For now, let's rule out `foo$bar` case as a first step. I'll probably think more on this later. Does it sound acceptable to you?

**Comment by randy3k** [comment]
LGTM. We could always improve it later.
