### ISSUE TITLE
Looking at a function definition triggers lintr

### ISSUE THREAD

**Issue by intiben** [REditorSupport/languageserver#213]
I noticed that when I open a function definition in VScode I get warnings from `lintr` about the code from that function e.g. here I looked at the `cowplot::plot_grid` function code and got:

![image](https://user-images.githubusercontent.com/56064362/74748610-15dbee00-5269-11ea-8553-a5a230fbab26.png)

Is there a way to disable this? I tried to exclude the `/tmp/` folder using the `.lintr` file but it broke the linting entirely.

**Comment by renkun-ken** [comment]
It is because opening a function definition creates a temp R script that contains the function code extracted from how R prints the function. and unfortunately `lintr` under default settings does not seem to like it, e.g. when there are infix operators like `/`, lintr likes to put spaces around all infix operators as your attached image suggests while R printing does not do this.

Maybe we could disable diagnostics for files from the temp dir to resolve this.

**Comment by intiben** [comment]
@renkun-ken thanks for your reply. I also came to the same conclusion as you this is why I tried to exclude `/tmp/` from lintr by adding the following to `.lintr` but lintr just stopped working then...
```
exclusions: list(list.files("/tmp", recursive = TRUE, full.names = TRUE, pattern = "\\.R$"))
```

**Comment by renkun-ken** [comment]
@intiben, we are considering moving to only linting documents inside the workspace. Does it make sense to you?

**Comment by intiben** [comment]
Yes that makes sense, thanks for taking my request into consideration.

**Comment by renkun-ken** [comment]
We are moving to the solution that we don't lint temp files unless the workspace is started from a temp directory, and closing a file outside workspace will remove its diagnostics.

Does it make sense to you?

**Comment by intiben** [comment]
Yes, thanks @renkun-ken

**Comment by renkun-ken** [comment]
Closing as fixed.
