### ISSUE TITLE
options set tabSize as 2 not work

### ISSUE THREAD

**Issue by beyondpie** [REditorSupport/languageserver#319]
Hi there,

this is a really nice package!
I have an issue when I set options(tabSize=2) in my .Rprofile under home directory. It seems that I still get tab as 4 when formmating.   But when I use the function below
```
options(languageserver.formatting_style = function(options) {
    styler::tidyverse_style(scope = "indention", indent_by = 2)
})
```
It works. I see in language server, `indent_by = options$tabSize`, but in R, we cannot get options in this way. We typically use `getOption("tabSize") or options()$tabSize`. Am I wrong at somewhere? 

Thanks,
Songpeng

**Comment by renkun-ken** [comment]
Thanks for reporting!

R does not have `tabSize` options. In fact, it comes from the code editor, i.e. `options$tabSize` does not mean `getOption("tabSize")` but code editor's options for the currently editing document including `tabSize`.

**Comment by beyondpie** [comment]
Thanks!
Interesting to know that
```
options(languageserver.formatting_style = function(options) {
    styler::tidyverse_style(scope = "indention", indent_by = 2)
})
```
The options are actually not the same. I am using Emacs with lsp-mode, do you have any suggesions on how to set this ? 

Thanks!

**Comment by renkun-ken** [comment]
Sorry, I have no experience using Emacs and its lsp-mode. To my knowledge, it seems all code editors should be able to set the indention of the document.

```r
options(languageserver.formatting_style = function(options) {
    styler::tidyverse_style(scope = "indention", indent_by = options$tabSize)
})
```

This option is intended to change the `scope` of formatting, not `indent_by = options$tabSize`. I suggest we always respect the document indention rather than override this here. You may need to change the indention behavior on your editor side.

**Comment by beyondpie** [comment]
Thank you very much!  I will close this issue.
