### ISSUE TITLE
I am not getting completeion with $

### ISSUE THREAD

**Issue by mguzmann** [REditorSupport/languageserver#340]
I am not sure whether this is on my side, but I don't get code completion when trying to access columns by name:

`df$`

does not complete to the possible columns.
I am using emacs+eglot but the same happens with lsp mode.

**Comment by renkun-ken** [comment]
Currently, languageserver does not provide completion for `$` to access `names()` of an object, which requires a live R session, i.e. languageserver only performs static code analysis without relying on a live R session at the moment.

Session-based completion could be done on editor side. For example, vscode-R session watcher supports completing `$`. In future, we might work out a general way to communicate with user R session so that other editors could do similar.

**Comment by mguzmann** [comment]
@renkun-ken Thanks for the answer. Is there any workaround people use?

**Comment by renkun-ken** [comment]
For the completion based on static analysis, related issues are #75, #158.

**Comment by renkun-ken** [comment]
>Is there any workaround people use?

Not sure about emacs+eglot. I saw emacs+ess seems to use native R completions.

**Comment by renkun-ken** [comment]
Closing as duplicate.

**Comment by ssh352** [comment]
had the same question as coc-r-lsp (uses languageserver) and neovim user.
