### ISSUE TITLE
Disable Lintr but keep other diagnostic errors

### ISSUE THREAD

**Issue by MCrates** [REditorSupport/languageserver#456]
I was looking to see if there was a way to disable or edit the lintr warnings generated when r.lsp Diagnostics were turned on?

The errors that are generated when it is enabled are extremely useful, however most/all of the lintr warnings are irrelevant to the code base we are working on.

Sorry if this question has already been posted, but I have been searching through all the issues and other sites trying to find out this information, any assistance would be appreciated!
Thank you

**Comment by renkun-ken** [comment]
Do you want to disable specific linters globally or disable linting for specific files or projects?

**Comment by renkun-ken** [comment]
Please take a look at https://github.com/jimhester/lintr#project-configuration which might be useful. Putting the config in `~/.lintr` takes effect globally, while `${workspaceFolder}` does only within the project.

**Comment by MCrates** [comment]
Thanks a bunch for that, 
It seems I was 99% of the way there, but I just couldn't figure out where exactly that .lintr file had to go in the context of VS Code.
Your comment helped me solve that, so thanks again!

**Comment by renkun-ken** [comment]
Currently, all diagnostics in VS Code come from lintr, i.e. a collection of linters each check a specific aspect of the code. The `.lintr` config will work no matter what IDE you use. If you edit your global lintr config (e.g. via `file.edit("~/.lintr")`) and put the following code in it:

```r
linters: with_defaults(
  line_length_linter(120), 
  commented_code_linter = NULL
)
```

then it will make all `lintr::lint()` deviate from the defaults with the specified settings above if `lint(linters=)` is not specified.

If you only want to change the linting of your particular project, then put the same file in your workspace folder. `lintr` will pick up this file instead of the global config file.

**Comment by renkun-ken** [comment]
You could take a look at the names of the linter you want to disable, and write them like `commented_code_linter = NULL` to disable them.

**Comment by MCrates** [comment]
Cool, this is exactly what I was after!
Thank you for the help and for all your work on getting R to work in VS Code.
I Appreciate it.
