### ISSUE TITLE
Re-factor can only find instances of function in opened files

### ISSUE THREAD

**Issue by gowerc** [REditorSupport/languageserver#519]
This might be a limitation of vscode rather than this extension but I thought I'd raise it anyway just encase (feel free to close if its a vscode issue)

**Describe the bug**
Using vscodes refactor features in an R package seems to only detect occurances in files that have been opened at least once during the session. If a file has not been opened then the occurance is not detected and it will be excluded from the renaming. 

![image](https://user-images.githubusercontent.com/8447209/152174120-2837f512-615a-4cbc-9c35-35014ecceb25.png)

In the above screenshot instances of the "draws" function are only shown from files that I have previously opened. If I haven't opened the file then the occourance of "draws" is not shown

**To Reproduce**

1. Create a function
2. Use it in several different files
3. Reset your vscode instance
4. only open 1 file using the function
5. right click -> "go to references"
6. only the instances in files that have been opened at least once will be shown

## Do you want to fix by self? (We hope your help!)

No

**Expected behavior**
that all instances would be shown even if the file hasn't yet been opened

**Environment (please complete the following information):**

- OS: macOS
- VSCode Version: 1.63.2
- R Version: 4.1.2
- vscode-R version: v2.3.6

**Comment by renkun-ken** [comment]
It is a known behavior of the language server, i.e. the language server provides language features such as find references, rename, etc. within the *language server workspace*. More specifically,

* If the editor workspace contains an R package, then the language server workspace contains all R files in `R`.
* Otherwise, the language server workspace only contains open files in the editor.

Related: #386

**Comment by gowerc** [comment]
@renkun-ken,

If i'm understanding you correctly, then the behaviour I'm experiancing is a bug because both of the files shown above are in the same project & folder  which is also an R package. Based on your description I wouldn't have expected the references for "validate" to work and those for "draws" not to work as they are both within the same R package

**Comment by renkun-ken** [comment]
From your screencasts, it seems that you are trying to find-reference or rename a symbol defined in `R/*.R` but used in `misc/*.R`. The language server workspace of an R package only contains R files in `R` folder but not others initiallly. As you open files in other folders, the language server workspace also contains those open files, so that find-reference and rename also cover those files.

**Comment by gowerc** [comment]
ah apologies well spotted I will close this then and put any more comments in the linked issue. Thank you for looking at this !
