### ISSUE TITLE
Quarto support?

### ISSUE THREAD

**Issue by H-Mateus** [REditorSupport/languageserver#575]
Are there any plans to add support for [Quarto](https://quarto.org/)?

It seems to work pretty well as is from some playing around in NeoVim, if one just adds the new filetype, but I notice the formating doesn't seem to work in .qmd files for some reason.

Also, not sure how feasible this is, but it'd be real neat if there could be completion for YAML/chunk options, similar to what RStudio provides

**Comment by eitsupi** [comment]
The quarto development team is planning to develop a language server for quarto, so it is better to wait for that.
quarto-dev/quarto-cli#239

**Comment by H-Mateus** [comment]
Ah, I wasn't aware of that, it sounds perfect, cheers!

**Comment by milanglacier** [comment]
Reading the discussion in the quarto issue, I think the quarto dev team is currently looking for a hack way to implement their language server: creating virtual documents associated with the language code blocks and call their corresponding language server in the virtual documents, and syncing the completion sources. It is really a hack. And A native support for the language server (say R)  to only R source code block would be much more easier.

Since the quarto document and rmarkdown document are extremely similar: code block are fenced with three backticks \`,
I think it wouldn't take much effort to adopt quarto support.

**Comment by jmbuhr** [comment]
Just to confirm this, the quarto language server indeed doesn't cover code completion but will complete things like references and yaml keys. The completion in code blocks is handled by these synchronized hidden documents. In the case of VS Code this is what the quarto extension does. For Neovim I implemented the same "hack" here: https://github.com/quarto-dev/quarto-nvim
There is also a getting started section for Neovim now: https://quarto.org/docs/get-started/hello/neovim.html
 
So while I agree that some sort of meta-langauge server to handled code blocks would be cool, I also got excited about the possibilities with this hack. Because now it (quarto-nvim) can work for **any** language, not just R. I have tested it with `R`, `python`, `julia`, `lua` and `haskell` so far :) 


PS @milanglacier : In a different issue I incorrectly stated that the R languageserver didn't work for Rmarkdown, so I was clearly not up to date on that one and deleted the comment to no confuse people.

**Comment by cderv** [comment]
I think it would be worth reopening this idea. We [discussed the fact](https://github.com/quarto-dev/quarto-cli/discussions/4269#discussioncomment-5710477) that it would be better for Quarto support in VSCODE if the languageserver part was indeed supported the same as in R file and Rmd file through this package for `.qmd` file too

Not sure what it means, but happy to help in any way.

**Comment by albersonmiranda** [comment]
@renkun-ken would you please consider reopen this one?

Apparently, for Linux (and I'm guessing mac also), temp file (intellisense.r) is been created in a root access directory (/tmp/tmp-*-*/r/). Since it's not recommended running vscode with sudo, I can't get completions.

Maybe change temp dir to /home/somewhere would fix it?

**Comment by luciorq** [comment]
@albersonmiranda, in both Linux and macOS, users can create directories and files inside the /tmp directory.

If your `/tmp/.../r` is owned by the root user, it is probably because VSCode or another program was invoked as the root user (by using `sudo`, for instance). Maybe you need to manually remove the directory so that when the plugin is stated by your user, it can create the directory with the right permissions.

As you already stated, you should not run VSCode as the root user.

**Comment by albersonmiranda** [comment]
@luciorq You're right! It doesn't seem to be related to access.

I went through the VSCode R extension files, and activation occurs when a .rmd file is detected in the editor. I managed to make it work for Quarto (i.e. activate completions) by making it interpret qmd files as rmd files. However, this overrides the Quarto extension, disabling its features (e.g., running "quarto render *" and YAML completions). I believe the Quarto extension should implement completions for qmd files.

What's bugging me now is why it works on Windows. Based on the documentation, it appears that VSCode R features shouldn't work with qmd files (as they don't work on Ubuntu and MacOS), since they're bound to .R and .Rmd extensions.
