### ISSUE TITLE
Completion dataframe variable/columns

### ISSUE THREAD

**Issue by PMassicotte** [REditorSupport/languageserver#638]
First, thank you for the work on `languageserver`.

I am using neovim and I would like to know if it is possible to get column names completion when using the pipe operator.

For example, inside `mutate()`, is it possible to have access to the `mtcars` columns?

![image](https://github.com/REditorSupport/languageserver/assets/4519221/45120bc5-b989-4e15-86da-4cb598a1468b)

**Comment by ktrutmann** [comment]
Hey, just so you have at least some answer:
Column name completion is generally not supported currently, because it would require the languageserver to hook into the active R session to grab the elements there. Currently the server is only analysing the script, and basically "only knows what's there". That means if you load some csv it has no way of knowing what the variable names will be.
With the `mtcars` dataframe you used as an example it's theoretically possible, because it stemms from a package. But that would be very inconsistent behavior then.
I remember this being mentioned in some other issue and I think it's not currently on the roadmap sadly.

**Comment by PMassicotte** [comment]
Thank you for the answer. 

It is now supported in [R.nvim](https://github.com/R-nvim)

![image](https://github.com/REditorSupport/languageserver/assets/4519221/927d7cb5-0371-4869-ab61-453a2b60ef09)
